### ISSUE TITLE
Configure error

### ISSUE THREAD

**Issue by tradetree** [sumeetchhetri/ffead-cpp#10]
After running autogen.sh successfully, running configure results in the following error:

./configure: line 23751: syntax error near unexpected token `else'
./configure: line 23751: `else'

This is from a clone of the latest release.  Version 1.9 configures/builds without error.

**Comment by sumeetchhetri** [comment]
To understand your issue better can you let me know the platform/OS you are building ffead-cpp on?

**Comment by tradetree** [comment]
Centos 6.7 final
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
uname -r
2.6.32-431.1.2.0.1.el6.x86_64

**Comment by sumeetchhetri** [comment]
Fixed the issue, was related to invalid substitution in configure.ac (ADD_LIBDL parameter). Please retest with the latest master.

**Comment by tradetree** [comment]
Great, configure and make work perfectly.  Thanks!
