### ISSUE TITLE
Building 2.0, running  ./autogen.sh fails:  MOD_APACHEMOD does not appear in AM_CONDITIONAL

### ISSUE THREAD

**Issue by lyp365859350** [sumeetchhetri/ffead-cpp#13]
**According to the steps:  https://github.com/sumeetchhetri/ffead-cpp/wiki/Hello-World**
running  ./ffead_gen.sh generate Hello Wold , after ./autogen.sh fails with the following error

libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:11: installing './compile'
configure.ac:5: installing './missing'
Makefile.am:243: error: MOD_APACHEMOD does not appear in AM_CONDITIONAL
Makefile.am:248: error: MOD_NGINXMOD does not appear in AM_CONDITIONAL
configure.ac:903: error: required file 'src/apache_mod_ffeadcpp/autotools/Makefile.in' not found
configure.ac:903: error: required file 'web/hello_world/src/autotools/Makefile.in' not found
src/autotools/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

**Comment by sumeetchhetri** [comment]
Have pushed a fix to resolve this, can you please pull the latest master and try again.

**Comment by lyp365859350** [comment]
thanks
