### ISSUE TITLE
Server not starting (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by nexasone** [sumeetchhetri/ffead-cpp#22]
Setup: ubuntu 18.04
           ffead-cpp from master branch
Following the quick start steps got the following
1- 
sudo apt update -yqq && sudo apt install -yqq autoconf-archive gcc g++ cmake unzip libssl-dev uuid-dev odbc-postgresql unixodbc unixodbc-dev libcurl4-openssl-dev libmemcached-dev libmongoc-dev libhiredis-dev wget netcat
-> success

2- libcuckoo problem due to adding namespace libcuckoo in its header files
     corrected by adding namespace libcuckoo::  to declaration in ffead sources
4- make install -> success
5- ./server.sh  waits for a while and then exists no server listening to 8080
attached are ffead.log and logs/job.log

[ffead.log](https://github.com/sumeetchhetri/ffead-cpp/files/3981350/ffead.log)
[jobs.log](https://github.com/sumeetchhetri/ffead-cpp/files/3981351/jobs.log)

Appreciate your help

**Comment by nexasone** [comment]
Another problem was

ffead-cpp-master/web/default/src/DefaultOAUTHController.cpp:41:65: error: conversion from ‘RMap {aka std::map<std::basic_string<char>, std::basic_string<char>, cicomp>}’ to non-scalar type ‘std::map<std::basic_string<char>, std::basic_string<char> >’ requested
  std::map<std::string,std::string> reqparams = req->getAllParams();
                                                ~~~~~~~~~~~~~~~~~^~

This has been solved by changing type of reqparams to std::map<std::string, std::string, cicomp> reqParams =  req->getAllParams();

--- Following instructions for Centos 7 gives
/server.sh: line 32:  8494 Segmentation fault      ./ffead-cpp $FFEAD_CPP_PATH > ffead.log 2>&1

**Comment by sumeetchhetri** [comment]
Huge apologies for this so very delayed response, Can you please pull the latest code and check once?

**Comment by sumeetchhetri** [comment]
There were some segfaults which were handled due to certain pointer related issues, which have been fixed in a lot of previous commits, I forgot to even look at this open issue for a long time, apologies again, do let me know if you see any issues with the latest code though.

**Comment by nexasone** [comment]
Thank you for your reply.
Unfortunately there is no luck. Same segmentation after downloading master from github.
Attached is the ffead.log file.
Regards

[ffead.log](https://github.com/sumeetchhetri/ffead-cpp/files/4334571/ffead.log)

**Comment by sumeetchhetri** [comment]
Actually the build instructions are incomplete, you need to perform,
`cmake -DMOD_SDORM_MONGO=on .` before doing,
`make install`
The MONGO DB ORM module needs to be built so that the te-benchmark* applications function properly.
I have updated the README accordingly

**Comment by sumeetchhetri** [comment]
@nexasone can we close this issue if the resolution works for you?
