### ISSUE TITLE
Dependencies not listed

### ISSUE THREAD

**Issue by mouse07410** [sumeetchhetri/ffead-cpp#35]
For example, `ffead-cpp` cannot build without `libcuckoo`. But it's never mentioned in the README, or elsewhere.

All the required dependencies should be listed in the README.

**Comment by sumeetchhetri** [comment]
There's an outdated version [here](https://github.com/sumeetchhetri/ffead-cpp/wiki/Prerequisites)
OS based instructions and detailed instructions can be found [here](https://github.com/sumeetchhetri/ffead-cpp/tree/master/docker)
Will get the README updated for sure!
